### ISSUE TITLE
Trying to confirm the unbreed command causes an error

### ISSUE THREAD

**Issue by XCharmyX** [Flashback083/Unbreed#2]
Doing "/unbreed {slot#} confirm" causes this error:

[23:24:13] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'unbreed 1 confirm' for source EntityPlayerMP['user'/10, l='world', x=1,28, y=75,78, z=236,67]: java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
        at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:165) ~[MinecraftCommandWrapper.class:1.12.2-2838-7.3.0]
        at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:146) ~[MinecraftCommandWrapper.class:1.12.2-2838-7.3.0]
        at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355) ~[SpongeCommandDispatcher.class:1.12.2-2838-7.3.0]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360) [SpongeCommandManager.class:1.12.2-2838-7.3.0]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219) [PacketPhaseUtil.class:1.12.2-2838-7.3.0]
        at net.minecraft.network.PacketThreadUtil$1.redirect$zlc000$impl$redirectToPhaseTracker(SourceFile:540) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_301]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_301]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:310) [SpongeImplHooks.class:1.12.2-2838-7.3.0]
        at net.minecraft.server.MinecraftServer.redirect$zjg000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[minecraft_server.1.12.2.jar:?]
        at com.pixelmonmod.pixelmon.api.storage.IStorageManager.getParty(IStorageManager.java:36) ~[IStorageManager.class:8.2.0]
        at fr.pokepixel.unbreed.UnbreedCmd.doBreeda(UnbreedCmd.java:198) ~[UnbreedCmd.class:?]
        at fr.pokepixel.unbreed.UnbreedCmd.func_184881_a(UnbreedCmd.java:108) ~[UnbreedCmd.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) ~[bj.class:?]
        at net.minecraft.command.CommandHandler.accessor$tryExecuteCommand(CommandHandler.java) ~[bj.class:?]
        at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:161) ~[MinecraftCommandWrapper.class:1.12.2-2838-7.3.0]
        ... 21 more

**Comment by Flashback083** [comment]
Hello what version of Unbreed ?
Are you on my discord ? Maybe try latest i have in it

**Comment by XCharmyX** [comment]
Hi. Im using the unbreed-4.0 version, the latest one i could find. Im having trouble finding a link to your discord, so im not in the discord. :)

**Comment by Flashback083** [comment]
Okay its seems its latest version, i'll check that asap, if you wanna get more info on the update you can check my discord: https://discord.gg/BhWFTPd

**Comment by XCharmyX** [comment]
Will do. Thank you :)
